name: asset-pricing
services:
  api:
    image: asset-pricing-api
    container_name: asset-pricing-api
    build:
      context: ../../
    ports:
      - 8080:8080
    environment:
      - PORT=8080
